server.port=9091

# Report-service-specific upload/report directories (prod — Linux/Docker paths)
file.upload-dir.Admin=/var/VST-DMS-APPS/REPORTS/Admin/
file.upload-dir.DealerMasterTemp=/var/VST-DMS-APPS/Template/dealer-master/
file.upload-dir.userActivityLogTemp=/var/VST-DMS-APPS/REPORTS/activity log/
file.upload-dir.ledgerTemplate=/var/VST-DMS-APPS/Template/Ledger Template/
