server.port=9091

# Report-service-specific upload/report directories (dev — Windows paths)
file.upload-dir.Admin=C:/VST-DMS-APPS/REPORTS/Admin/
file.upload-dir.DealerMasterTemp=C:/VST-DMS-APPS/Template/dealer-master/
file.upload-dir.userActivityLogTemp=C:/VST-DMS-APPS/REPORTS/activity log/
file.upload-dir.ledgerTemplate=C:/VST-DMS-APPS/Template/Ledger Template/
