spring:
  datasource:
    url: jdbc:sqlserver://<UAT_SQL_HOST>:1433;databaseName=VST_DMS;trustServerCertificate=true
    username: <UAT_SQL_USER>
    password: <UAT_SQL_PASSWORD>

security:
  rabbitmq:
    host: <UAT_RABBITMQ_HOST>
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100

eureka:
  client:
    service-url:
      defaultZone: https://vstdlr.vstshakti.in/eureka/
  instance:
    hostname: vstdlr.vstshakti.in
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}

file:
  upload-dir:
    Temp: /var/VST-DMS-APPS/FILES/Temp/
    Main: /var/VST-DMS-APPS/FILES/
