spring:
  datasource:
    url: jdbc:sqlserver://192.9.200.52:1433;databaseName=VST_DMS;trustServerCertificate=true
    username: sa
    password: 'VST.2022#'

security:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}    

file:
  upload-dir:
    Temp: C:/VST-DMS-APPS/FILES/Temp/
    Main: C:/VST-DMS-APPS/FILES/
