eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  security:
    oauth2:
      resource:
        token-info-uri: http://Micro-Auth-Service:9191/auth-api/oauth/check_token
      client:
        client-id: vst-dms-view-client
        client-secret: cnhindglobal

security:
  oauth2:
    resource:
      token-info-uri: ${spring.security.oauth2.resource.token-info-uri}
    client:
      client-id: ${spring.security.oauth2.client.client-id}
      client-secret: ${spring.security.oauth2.client.client-secret}
  mail:
    host: 192.9.200.204
    port: 587
    username: itsupport@vsttillers.com
    password: vst.2017
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jdbc:
  url: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}
  urlForReports: ${spring.datasource.url}
  usernameForReports: ${spring.datasource.username}
  passwordForReports: ${spring.datasource.password}

mail_forgot_password:
  queue: forgotpassword.queue
  exchange: forgotpassword.exchange
  routing_key: forgot.password.routing.key

mail_change_password:
  queue: changepassword.queue
  exchange: changepassword.exchange
  routing_key: changepassword.routing.key

mail_create_enq:
  queue: enqCreate.queue
  exchange: enqCreate.exchange
  routing_key: enqCreate.routing.key

mail_validated_enq:
  queue: enqvalidated.queue
  exchange: enqvalidated.exchange
  routing_key: enqvalidated.routing.key

mail_followup_enq:
  queue: followupenq.queue
  exchange: followupenq.exchange
  routing_key: followupenq.routing.key

mail_retailfollowup_enq:
  queue: retailfollowupenq.queue
  exchange: retailfollowupenq.exchange
  routing_key: retailfollowupenq.routing.key
