spring:
  datasource:
    url: jdbc:sqlserver://<PROD_SQL_HOST>:1433;databaseName=VST_DMS;trustServerCertificate=true
    username: <PROD_SQL_USER>
    password: <PROD_SQL_PASSWORD>

security:
  rabbitmq:
    host: <PROD_RABBITMQ_HOST>
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server/eureka/
  instance:
    hostname: vstdms.vstshakti.in
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}      

file:
  upload-dir:
    Temp: /var/VST-DMS-APPS/FILES/Temp/
    Main: /var/VST-DMS-APPS/FILES/
