server.port=9191
security.signing-key=MaYzkSjmkzPC57L
security.encoding-strength=256
security.security-realm=HiTeChRealm

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/     
eureka.instance.lease-expiration-duration-in-seconds=5
eureka.instance.lease-renewal-interval-in-seconds=2

file.upload-dir.Temp=C:/VST-DMS-APPS/FILES/Temp/
file.upload-dir.Main=C:/VST-DMS-APPS/FILES/

jdbc.urlForReports=jdbc:sqlserver://192.9.200.204:1433;databaseName=VST_DMS;
jdbc.usernameForReports=admin
jdbc.passwordForReports=YOUR_REPORT_DB_PASSWORD
