server.port=9191
security.signing-key=MaYzkSjmkzPC57L

eureka.client.serviceUrl.defaultZone=http://Micro-Eureka-Service:8761/eureka/
eureka.instance.lease-expiration-duration-in-seconds=30
eureka.instance.lease-renewal-interval-in-seconds=10

file.upload-dir.Temp=/var/VST-DMS-APPS/FILES/Temp/
file.upload-dir.Main=/var/VST-DMS-APPS/FILES/

# ── Database ─────────────────────────────────────────────────────────────────
jdbc.url=${DB_URL}
jdbc.username=${DB_USERNAME}
jdbc.password=${DB_PASSWORD}
