server.port=9191
  security.encoding-strength=256
  security.security-realm=HiTeChRealm

  # Report DB — falls back to main DB since report DB not in use
  jdbc.urlForReports=${jdbc.url}
  jdbc.usernameForReports=${jdbc.username}
  jdbc.passwordForReports=${jdbc.password}
