server:
  port: 9999
  servlet:
    context-path: /emailService
    session:
      cookie:
        http-only: true
        secure: false
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    banner-mode: off
    allow-circular-references: true
    allow-bean-definition-overriding: true
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  thymeleaf:
    cache: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: ${MAIL_HOST:192.9.200.204}
    port: 587
    username: ${MAIL_USERNAME:itsupport@vsttillers.com}
    password: ${MAIL_PASSWORD:vst.2017}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: '5000'
          timeout: '5000'
          writetimeout: '5000'
          starttls:
            enable: true
            required: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
  endpoint:
    auditevents:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        loggerLevel: BASIC
      postFeignClient:
        loggerLevel: FULL

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /swagger-ui-custom.html

logging:
  level:
    root: INFO
    com.hitech: INFO
    org.springframework.security: INFO
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    com.sun.jersey: WARN
    org.apache.http: WARN
