context:
  path: /gateway

spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth-api/oauth/token,/auth-api/**,/gateway/auth-api/oauth/token,/gateway/auth-api/**
            - Method=POST,GET,DELETE
          filters:
            - RewritePath=/gateway(?<segment>/?.*), $\{segment}

        - id: administration-server
          uri: lb://administration-server
          predicates:
            - Path=${context.path}/administration/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: administration-server-report
          uri: lb://administration-server-report
          predicates:
            - Path=${context.path}/administrationReport/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: common-services
          uri: lb://common-services
          predicates:
            - Path=${context.path}/common/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: presales-enquiry-report
          uri: lb://presales-enquiry-report
          predicates:
            - Path=${context.path}/presaleEnquiryReport/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: presales-enquiry
          uri: lb://presales-enquiry
          predicates:
            - Path=${context.path}/presaleEnquiry/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: presales-activity-report
          uri: lb://presales-activity-report
          predicates:
            - Path=${context.path}/presaleActivityReport/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: presales-activity
          uri: lb://presales-activity
          predicates:
            - Path=${context.path}/presaleActivity/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: presales-scheme
          uri: lb://presales-scheme
          predicates:
            - Path=${context.path}/presalescheme/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: sales-order
          uri: lb://sales-order
          predicates:
            - Path=${context.path}/saleOrder/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: sales-customerpurchase
          uri: lb://sales-customerpurchase
          predicates:
            - Path=${context.path}/salecustomerpurchase/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: sales-stocktransfer
          uri: lb://sales-stocktransfer
          predicates:
            - Path=${context.path}/salestocktransfer/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: sales-miscellaneous
          uri: lb://sales-miscellaneous
          predicates:
            - Path=${context.path}/salesmiscellaneous/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: service
          uri: lb://service
          predicates:
            - Path=${context.path}/service/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: service-customer
          uri: lb://service-customer
          predicates:
            - Path=${context.path}/servicecustomer/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: service-warranty
          uri: lb://service-warranty
          predicates:
            - Path=${context.path}/servicewarranty/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: service-requisition
          uri: lb://service-requisition
          predicates:
            - Path=${context.path}/servicerequisition/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: service-spare
          uri: lb://service-spare
          predicates:
            - Path=${context.path}/servicespare/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: service-email
          uri: lb://service-email
          predicates:
            - Path=${context.path}/emailService/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

        - id: service-report
          uri: lb://service-report
          predicates:
            - Path=${context.path}/servicereport/**
            - Method=POST,GET
          filters:
            - RewritePath=${context.path}(?<segment>/?.*), $\{segment}

server:
  port: 8080
  max-http-header-size: 65536
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 50s
        cancel-running-future: false
    instances:
      backendB:
        timeout-duration: 250ms

info:
  app:
    name: ${spring.application.name}
    description: API Gateway - VST DMS
    version: "@project.version@"

logging:
  level:
    root: INFO
    com.hitech: INFO
    org.springframework.cloud.gateway: INFO
