spring:
  thymeleaf:
    cache: false

file:
  upload-dir:
    Report: C:/VST-DMS-APPS/REPORTS/
    EnquiryReport: C:/VST-DMS-APPS/REPORTS/ENQ/
    summaryReport: C:/VST-DMS-APPS/REPORTS/SUMMARY/
    TocReport: C:/VST-DMS-APPS/REPORTS/TOC/
    GoodsTransit: C:/VST-DMS-APPS/REPORTS/Goods-Transit/
    AdvanceTrackingReport: C:/VST-DMS-APPS/advanceTrackingReport/AdvanceReport/
    dashboardEnquiryReport: C:/VST-DMS-APPS/REPORTS/enqdashboard/
    weederReport: C:/VST-DMS-APPS/REPORTS/weederreport/

logging:
  level:
    root: INFO
    com.hitech: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    com.sun.jersey: WARN
    org.apache.http: WARN
