server.port=8087

# Service-specific report directories (UAT — Linux/Docker paths)
file.upload-dir.Report=/var/VST-DMS-APPS/REPORTS/
file.upload-dir.EnquiryReport=/var/VST-DMS-APPS/REPORTS/ENQ/
file.upload-dir.AdvanceTrackingReport=/var/VST-DMS-APPS/advanceTrackingReport/AdvanceReport/
