server.port=8086

# Report-service-specific directories (prod — Linux/Docker paths)
file.upload-dir.Report=/var/VST-DMS-APPS/REPORTS/
file.upload-dir.EnquiryReport=/var/VST-DMS-APPS/REPORTS/ENQ/
file.upload-dir.summaryReport=/var/VST-DMS-APPS/REPORTS/SUMMARY/
file.upload-dir.TocReport=/var/VST-DMS-APPS/REPORTS/TOC/
file.upload-dir.GoodsTransit=/var/VST-DMS-APPS/REPORTS/Goods-Transit/
file.upload-dir.AdvanceTrackingReport=/var/VST-DMS-APPS/advanceTrackingReport/AdvanceReport/
file.upload-dir.dashboardEnquiryReport=/var/VST-DMS-APPS/REPORTS/enqdashboard/
file.upload-dir.weederReport=/var/VST-DMS-APPS/REPORTS/weederreport/
