server.port=8091

# Service-specific report directories (UAT — Linux/Docker paths)
file.upload-dir.Report=/var/VST-DMS-APPS/REPORTS/Allotment/
file.upload-dir.Reporttwo=/var/VST-DMS-APPS/REPORTS/Delivery Challan/
file.upload-dir.Reportthree=/var/VST-DMS-APPS/REPORTS/machine invoice/
file.upload-dir.PartySearchReport=/var/VST-DMS-APPS/REPORTS/partyMaster/
file.upload-dir.ReportActivitySearch=/var/VST-DMS-APPS/REPORTS/activity search detail/
file.upload-dir.ReportActivityPlanSearch=/var/VST-DMS-APPS/REPORTS/activity plan detail/
file.upload-dir.ReportPlanApproval=/var/VST-DMS-APPS/REPORTS/plan approval/
file.upload-dir.ReportQuotationval=/var/VST-DMS-APPS/REPORTS/Quotation/
file.upload-dir.PARTYMASTER=/var/VST-DMS-APPS/FILES/Temp/
file.upload-dir.gstInvoice=/var/VST-DMS-APPS/REPORTS/gst invoice/
file.upload-dir.vstUserPath=/var/VST-DMS-APPS/REPORTS/vst user/
file.upload-dir.orgHierPath=/var/VST-DMS-APPS/REPORTS/field org/
