server:
  port: 8091
  servlet:
    context-path: /salecustomerpurchase
    session:
      cookie:
        http-only: true
        secure: false
  max-http-header-size: 65536
  tomcat:
    max-http-header-size: 131072
    max-http-post-size: 10485760
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    banner-mode: off
    allow-circular-references: true
    allow-bean-definition-overriding: true
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  thymeleaf:
    cache: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir:
    Report: /var/VST-DMS-APPS/REPORTS/Allotment/
    Reporttwo: /var/VST-DMS-APPS/REPORTS/Delivery Challan/
    Reportthree: /var/VST-DMS-APPS/REPORTS/machine invoice/
    PartySearchReport: /var/VST-DMS-APPS/REPORTS/partyMaster/
    ReportActivitySearch: /var/VST-DMS-APPS/REPORTS/activity search detail/
    ReportActivityPlanSearch: /var/VST-DMS-APPS/REPORTS/activity plan detail/
    ReportPlanApproval: /var/VST-DMS-APPS/REPORTS/plan approval/
    ReportQuotationval: /var/VST-DMS-APPS/REPORTS/Quotation/
    PARTYMASTER: /var/VST-DMS-APPS/FILES/Temp/
    gstInvoice: /var/VST-DMS-APPS/REPORTS/gst invoice/
    vstUserPath: /var/VST-DMS-APPS/REPORTS/vst user/
    orgHierPath: /var/VST-DMS-APPS/REPORTS/field org/

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans
  endpoint:
    auditevents:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        loggerLevel: BASIC
      postFeignClient:
        loggerLevel: FULL

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /swagger-ui-custom.html

logging:
  level:
    root: INFO
    com.hitech: INFO
    org.springframework.security: INFO
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    com.sun.jersey: WARN
    org.apache.http: WARN
