server.port=8090

# Service-specific file directories (UAT — Linux/Docker paths)
file.upload-dir.Temp=/var/VST-DMS-APPS/FILES/Temp/
file.upload-dir.Main=/var/VST-DMS-APPS/FILES/
file.upload-dir.Report=/var/VST-DMS-APPS/REPORTS/pdi/
file.upload-dir.ReportTwo=/var/VST-DMS-APPS/REPORTS/grn/
file.upload-dir.ReportThree=/var/VST-DMS-APPS/REPORTS/machine po/
file.upload-dir.ReportFour=/var/VST-DMS-APPS/REPORTS/purchase return/
file.upload-dir.ReportFive=/var/VST-DMS-APPS/REPORTS/gst invoice/
file.upload-dir.StockTemplate=/var/VST-DMS-APPS/Template/Stock Template/
file.upload-dir.Reports=/var/VST-DMS-APPS/REPORTS/Stock/
