server.port=8095

# Service-specific file directories (dev — Windows paths)
file.upload-dir.Temp=C:/VST-DMS-APPS/FILES/Temp/
file.upload-dir.Main=C:/VST-DMS-APPS/FILES/
file.upload-dir.SpareTemplate=C:/VST-DMS-APPS/Template/Spare Template/
file.upload-dir.OldChassisReports=C:/VST-DMS-APPS/OLDCHASSISREPORTS/OldChassis/
file.upload-dir.QuotationReports=C:/VST-DMS-APPS/REPORTS/Quotation/
file.upload-dir.BookingReports=C:/VST-DMS-APPS/BOOKINGREPORTS/ServiceBooking/
file.upload-dir.RequisitionReports=C:/VST-DMS-APPS/REQUISITIONREPORTS/Requisition/
file.upload-dir.SpareIssueReports=C:/VST-DMS-APPS/REPORTS/SpareIssue/
file.upload-dir.SpareReturnReports=C:/VST-DMS-APPS/REPORTS/SpareReturn/
file.upload-dir.RequisitionPrint=C:/VST-DMS-APPS/REPORTS/RequsitonPrint/
file.upload-dir.ActivityGstClaimInvPrint=C:/VST-DMS-APPS/REPORTS/ActGstInvClaim/
