server.port=9099

# Service-specific file directories (UAT — Linux/Docker paths)
file.upload-dir.Temp=/var/VST-DMS-APPS/FILES/Temp/
file.upload-dir.Main=/var/VST-DMS-APPS/FILES/
file.upload-dir.SpareTemplate=/var/VST-DMS-APPS/template/template/
file.upload-dir.customerTemplate=/var/VST-DMS-APPS/template/customer-order/
file.upload-dir.DcTemplate=/var/VST-DMS-APPS/REPORTS/Delivery Challan/Excel/
file.upload-dir.DcPdfTemplate=/var/VST-DMS-APPS/REPORTS/Delivery Challan/pdf/
file.upload-dir.InvoiceReturnDOc=/var/VST-DMS-APPS/template/InvoiceReturn/
file.upload-dir.SparePoPrintReport=/var/VST-DMS-APPS/REPORTS/SparePo/Print/
file.upload-dir.CouponManagementReport=/var/VST-DMS-APPS/REPORTS/CouponManagement/
file.upload-dir.InvoiceReturnReport=/var/VST-DMS-APPS/REPORTS/InvoiceReturn/
file.upload-dir.CoTemplate=/var/VST-DMS-APPS/REPORTS/Customer-Order/Excel/
file.upload-dir.Grn=/var/VST-DMS-APPS/REPORTS/spare/Excel/Grn/
file.upload-dir.GrnPrint=/var/VST-DMS-APPS/REPORTS/spare/Print/Grn/
file.upload-dir.InventoryTransfer=/var/VST-DMS-APPS/REPORTS/spare/Excel/InventoryTransfer/
file.upload-dir.Claim=/var/VST-DMS-APPS/REPORTS/spare/Excel/Claim/
file.upload-dir.BranchTransferIndent=/var/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Indent/
file.upload-dir.BranchTransferIssue=/var/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Issue/
file.upload-dir.BranchTransferReceipt=/var/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Receipt/
file.upload-dir.PickList=/var/VST-DMS-APPS/REPORTS/spare/Print/Picklist/
file.upload-dir.SaleInvoice=/var/VST-DMS-APPS/REPORTS/spare/Excel/SaleInvoice/
file.upload-dir.SaleInvoicePrint=/var/VST-DMS-APPS/REPORTS/spare/Print/SaleInvoice/
file.upload-dir.SpareClaimUpload=/var/VST-DMS-APPS/Micro-Frontend_Apps/dms-service-requisition/assets
file.upload-dir.InvoiceQRCodeUpload=/var/VST-DMS-APPS/Micro-Frontend_Apps/dms-service-requisition/assets/invoiceQR
file.upload-dir.cdTemplate=/var/VST-DMS-APPS/REPORTS/Credit-Debit-Note/pdf/
file.upload-dir.pvTemplate=/var/VST-DMS-APPS/REPORTS/Payment-Voucher/pdf/
file.upload-dir.pvExcelTemplate=/var/VST-DMS-APPS/REPORTS/Payment-Voucher/Excel/
file.upload-dir.cdnExcelTemplate=/var/VST-DMS-APPS/REPORTS/Credit-Debit-Note/Excel/
file.upload-dir.partInvoiceTemplate=/var/VST-DMS-APPS/REPORTS/Part-Invoice/Excel/
file.upload-dir.kpdOrderStatusTemplate=/var/VST-DMS-APPS/REPORTS/Kpd-Order-Status/Excel/
file.upload-dir.partGrnTemplate=/var/VST-DMS-APPS/REPORTS/Part-Grn/Excel/
file.upload-dir.partStockTemplate=/var/VST-DMS-APPS/REPORTS/Part-Stock/Excel/
file.upload-dir.poStatusTemplate=/var/VST-DMS-APPS/REPORTS/Po-Status/Excel/
file.upload-dir.aprReturnTemplate=/var/VST-DMS-APPS/REPORTS/Apr-Return/Excel/
file.upload-dir.aprPdfTemplate=/var/VST-DMS-APPS/REPORTS/Apr-Return/Pdf/
