spring:
  thymeleaf:
    cache: false

file:
  upload-dir:
    SpareTemplate: C:/VST-DMS-APPS/template/template/
    customerTemplate: C:/VST-DMS-APPS/template/customer-order/
    DcTemplate: C:/VST-DMS-APPS/REPORTS/Delivery Challan/Excel/
    DcPdfTemplate: C:/VST-DMS-APPS/REPORTS/Delivery Challan/pdf/
    InvoiceReturnDOc: C:/VST-DMS-APPS/template/InvoiceReturn/
    SparePoPrintReport: C:/VST-DMS-APPS/REPORTS/SparePo/Print/
    CouponManagementReport: C:/VST-DMS-APPS/REPORTS/CouponManagement/
    InvoiceReturnReport: C:/VST-DMS-APPS/REPORTS/InvoiceReturn/
    CoTemplate: C:/VST-DMS-APPS/REPORTS/Customer-Order/Excel/
    Grn: C:/VST-DMS-APPS/REPORTS/spare/Excel/Grn/
    GrnPrint: C:/VST-DMS-APPS/REPORTS/spare/Print/Grn/
    InventoryTransfer: C:/VST-DMS-APPS/REPORTS/spare/Excel/InventoryTransfer/
    Claim: C:/VST-DMS-APPS/REPORTS/spare/Excel/Claim/
    BranchTransferIndent: C:/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Indent/
    BranchTransferIssue: C:/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Issue/
    BranchTransferReceipt: C:/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Receipt/
    PickList: C:/VST-DMS-APPS/REPORTS/spare/Print/Picklist/
    SaleInvoice: C:/VST-DMS-APPS/REPORTS/spare/Excel/SaleInvoice/
    SaleInvoicePrint: C:/VST-DMS-APPS/REPORTS/spare/Print/SaleInvoice/
    SpareClaimUpload: C:/VST-DMS-APPS/Micro-Frontend_Apps/dms-service-requisition/assets
    InvoiceQRCodeUpload: C:/VST-DMS-APPS/Micro-Frontend_Apps/dms-service-requisition/assets/invoiceQR
    cdTemplate: C:/VST-DMS-APPS/REPORTS/Credit-Debit-Note/pdf/
    pvTemplate: C:/VST-DMS-APPS/REPORTS/Payment-Voucher/pdf/
    pvExcelTemplate: C:/VST-DMS-APPS/REPORTS/Payment-Voucher/Excel/
    cdnExcelTemplate: C:/VST-DMS-APPS/REPORTS/Credit-Debit-Note/Excel/
    partInvoiceTemplate: C:/VST-DMS-APPS/REPORTS/Part-Invoice/Excel/
    kpdOrderStatusTemplate: C:/VST-DMS-APPS/REPORTS/Kpd-Order-Status/Excel/
    partGrnTemplate: C:/VST-DMS-APPS/REPORTS/Part-Grn/Excel/
    partStockTemplate: C:/VST-DMS-APPS/REPORTS/Part-Stock/Excel/
    poStatusTemplate: C:/VST-DMS-APPS/REPORTS/Po-Status/Excel/
    aprReturnTemplate: C:/VST-DMS-APPS/REPORTS/Apr-Return/Excel/
    aprPdfTemplate: C:/VST-DMS-APPS/REPORTS/Apr-Return/Pdf/

logging:
  level:
    root: DEBUG
    com.hitech: DEBUG
    org.springframework.security: DEBUG
