server.port=9099

# Service-specific file directories (dev — Windows paths)
file.upload-dir.Temp=C:/VST-DMS-APPS/FILES/Temp/
file.upload-dir.Main=C:/VST-DMS-APPS/FILES/
file.upload-dir.SpareTemplate=C:/VST-DMS-APPS/template/template/
file.upload-dir.customerTemplate=C:/VST-DMS-APPS/template/customer-order/
file.upload-dir.DcTemplate=C:/VST-DMS-APPS/REPORTS/Delivery Challan/Excel/
file.upload-dir.DcPdfTemplate=C:/VST-DMS-APPS/REPORTS/Delivery Challan/pdf/
file.upload-dir.InvoiceReturnDOc=C:/VST-DMS-APPS/template/InvoiceReturn/
file.upload-dir.SparePoPrintReport=C:/VST-DMS-APPS/REPORTS/SparePo/Print/
file.upload-dir.CouponManagementReport=C:/VST-DMS-APPS/REPORTS/CouponManagement/
file.upload-dir.InvoiceReturnReport=C:/VST-DMS-APPS/REPORTS/InvoiceReturn/
file.upload-dir.CoTemplate=C:/VST-DMS-APPS/REPORTS/Customer-Order/Excel/
file.upload-dir.Grn=C:/VST-DMS-APPS/REPORTS/spare/Excel/Grn/
file.upload-dir.GrnPrint=C:/VST-DMS-APPS/REPORTS/spare/Print/Grn/
file.upload-dir.InventoryTransfer=C:/VST-DMS-APPS/REPORTS/spare/Excel/InventoryTransfer/
file.upload-dir.Claim=C:/VST-DMS-APPS/REPORTS/spare/Excel/Claim/
file.upload-dir.BranchTransferIndent=C:/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Indent/
file.upload-dir.BranchTransferIssue=C:/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Issue/
file.upload-dir.BranchTransferReceipt=C:/VST-DMS-APPS/REPORTS/spare/Excel/BranchTransfer/Receipt/
file.upload-dir.PickList=C:/VST-DMS-APPS/REPORTS/spare/Print/Picklist/
file.upload-dir.SaleInvoice=C:/VST-DMS-APPS/REPORTS/spare/Excel/SaleInvoice/
file.upload-dir.SaleInvoicePrint=C:/VST-DMS-APPS/REPORTS/spare/Print/SaleInvoice/
file.upload-dir.SpareClaimUpload=C:/VST-DMS-APPS/Micro-Frontend_Apps/dms-service-requisition/assets
file.upload-dir.InvoiceQRCodeUpload=C:/VST-DMS-APPS/Micro-Frontend_Apps/dms-service-requisition/assets/invoiceQR
file.upload-dir.cdTemplate=C:/VST-DMS-APPS/REPORTS/Credit-Debit-Note/pdf/
file.upload-dir.pvTemplate=C:/VST-DMS-APPS/REPORTS/Payment-Voucher/pdf/
file.upload-dir.pvExcelTemplate=C:/VST-DMS-APPS/REPORTS/Payment-Voucher/Excel/
file.upload-dir.cdnExcelTemplate=C:/VST-DMS-APPS/REPORTS/Credit-Debit-Note/Excel/
file.upload-dir.partInvoiceTemplate=C:/VST-DMS-APPS/REPORTS/Part-Invoice/Excel/
file.upload-dir.kpdOrderStatusTemplate=C:/VST-DMS-APPS/REPORTS/Kpd-Order-Status/Excel/
file.upload-dir.partGrnTemplate=C:/VST-DMS-APPS/REPORTS/Part-Grn/Excel/
file.upload-dir.partStockTemplate=C:/VST-DMS-APPS/REPORTS/Part-Stock/Excel/
file.upload-dir.poStatusTemplate=C:/VST-DMS-APPS/REPORTS/Po-Status/Excel/
file.upload-dir.aprReturnTemplate=C:/VST-DMS-APPS/REPORTS/Apr-Return/Excel/
file.upload-dir.aprPdfTemplate=C:/VST-DMS-APPS/REPORTS/Apr-Return/Pdf/
