server.port=8096

# Service-specific file directories (UAT — Linux/Docker paths)
file.upload-dir.Temp=/var/VST-DMS-APPS/FILES/Temp/
file.upload-dir.Main=/var/VST-DMS-APPS/FILES/
file.upload-dir.JobCardReport=/var/VST-DMS-APPS/REPORTS/jobcard preInvoice/
file.upload-dir.JobCardOpenReport=/var/VST-DMS-APPS/REPORTS/JobCard Open/
file.upload-dir.JobCardBillingReport=/var/VST-DMS-APPS/REPORTS/JobCard Billing/
file.upload-dir.jobCardReports=/var/VST-DMS-APPS/REPORTS/jobCardExcel/
file.upload-dir.BillingReports=/var/VST-DMS-APPS/REPORTS/Billing/
file.upload-dir.reminderServiceTemplate=/var/VST-DMS-APPS/REPORTS/Reminder-Service/Excel/
file.upload-dir.servicePlanStatusTemplate=/var/VST-DMS-APPS/REPORTS/Plan-Status/Excel/
file.upload-dir.historyCardServiceTemplate=/var/VST-DMS-APPS/REPORTS/History-Card/Excel/
file.upload-dir.serviceJobcardImageDownload=/var/VST-DMS-APPS/FILES/dms-service-customer/images/
